services:
  db:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  booking:
    image: booking_app
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env
    depends_on:
      - db
    command: sh /booking/docker/app.sh
    ports:
      - 7777:8000

volumes:
  postgresdata:
