"""Initial migration 04

Revision ID: 249a1cec744d
Revises: b2359a95253c
Create Date: 2024-12-24 00:49:40.204589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249a1cec744d'
down_revision: Union[str, None] = 'b2359a95253c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('hourly_rate', sa.Integer(), nullable=True))

    op.execute("UPDATE zones SET hourly_rate = 0 WHERE hourly_rate IS NULL")

    op.alter_column('zones', 'hourly_rate', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'hourly_rate')
    # ### end Alembic commands ###
