"""Initial migration 03

Revision ID: b2359a95253c
Revises: 90261390d284
Create Date: 2024-12-23 22:40:56.089579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2359a95253c'
down_revision: Union[str, None] = '90261390d284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime_from', sa.DateTime(), nullable=False),
    sa.Column('datetime_to', sa.DateTime(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), sa.Computed('EXTRACT(EPOCH FROM (datetime_to - datetime_from)) / 3600 * hourly_rate', ), nullable=True),
    sa.Column('total_hours', sa.Integer(), sa.Computed('EXTRACT(EPOCH FROM (datetime_to - datetime_from)) / 3600', ), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
